#!/bin/bash

echo "=========================================="
echo "  Railway 数据库连接信息查找指南"
echo "=========================================="
echo ""
echo "方法 1：查找 DATABASE_URL（最简单）"
echo "----------------------------------------"
echo "1. 在 Railway 项目页面，找到 'PostgreSQL' 或 'Database' 服务"
echo "2. 点击该服务"
echo "3. 点击 'Variables' 标签"
echo "4. 查找 'DATABASE_URL' 变量"
echo "5. 复制它的值"
echo ""
echo "方法 2：如果没有 DATABASE_URL，使用单独变量"
echo "----------------------------------------"
echo "在 Variables 标签中查找以下变量："
echo "  - PGHOST (主机地址)"
echo "  - PGPORT (端口，通常是 5432)"
echo "  - PGUSER (用户名，通常是 postgres)"
echo "  - PGPASSWORD (密码)"
echo "  - PGDATABASE (数据库名)"
echo ""
echo "方法 3：如果还没有数据库服务"
echo "----------------------------------------"
echo "1. 在项目页面点击 '+ New'"
echo "2. 选择 'Database'"
echo "3. 选择 'Add PostgreSQL'"
echo "4. Railway 会自动创建数据库"
echo ""
echo "=========================================="
echo ""
echo "找到连接信息后，请告诉我："
echo "  - 如果有 DATABASE_URL，直接告诉我"
echo "  - 如果有单独的变量，告诉我它们的值"
echo ""
