ALTER TABLE venue ADD COLUMN IF NOT EXISTS supports_walk_in BOOLEAN;
ALTER TABLE venue ADD COLUMN IF NOT EXISTS supports_full_court BOOLEAN;
ALTER TABLE venue ADD COLUMN IF NOT EXISTS walk_in_price INTEGER;
ALTER TABLE venue ADD COLUMN IF NOT EXISTS full_court_price INTEGER;