-- 添加缺失的列（如果不存在）
-- 在数据库控制台执行此脚本

ALTER TABLE venue ADD COLUMN IF NOT EXISTS supports_walk_in BOOLEAN;
ALTER TABLE venue ADD COLUMN IF NOT EXISTS supports_full_court BOOLEAN;
ALTER TABLE venue ADD COLUMN IF NOT EXISTS walk_in_price_min INTEGER;
ALTER TABLE venue ADD COLUMN IF NOT EXISTS walk_in_price_max INTEGER;
ALTER TABLE venue ADD COLUMN IF NOT EXISTS full_court_price_min INTEGER;
ALTER TABLE venue ADD COLUMN IF NOT EXISTS full_court_price_max INTEGER;
ALTER TABLE venue ADD COLUMN IF NOT EXISTS requires_reservation BOOLEAN;
ALTER TABLE venue ADD COLUMN IF NOT EXISTS reservation_method VARCHAR(200);
ALTER TABLE venue ADD COLUMN IF NOT EXISTS players_per_side VARCHAR(20);
ALTER TABLE venue ADD COLUMN IF NOT EXISTS has_rest_area BOOLEAN;
ALTER TABLE venue ADD COLUMN IF NOT EXISTS has_fence BOOLEAN;
ALTER TABLE venue ADD COLUMN IF NOT EXISTS has_shower BOOLEAN;
ALTER TABLE venue ADD COLUMN IF NOT EXISTS has_locker BOOLEAN;
ALTER TABLE venue ADD COLUMN IF NOT EXISTS has_shop BOOLEAN;
